### ISSUE TITLE
Upload New Record

### ISSUE THREAD

**Issue by lamorie** [MarkGalloway/RIS#23]
Record includes an ID, a patient, doctor, radiologist, test, prescribing date and test date, diagnosis and a short description

**Comment by lamorie** [comment]
Only accessible when using an Admin account

**Comment by MarkGalloway** [comment]
I believe by the spec that Radiologists upload these, however I don't see why an admin wouldn't be able to also.

**Comment by MarkGalloway** [comment]
Since images is in a separate issue, closing.
